active = "default"

[profiles.default]
PREFECT_LOCAL_STORAGE_PATH = "/home/shekhar/shekhar/test/AlgorithmicTrading"
PREFECT_HOME = "/home/shekhar/shekhar/test/AlgorithmicTrading"
PREFECT_API_URL = "http://0.0.0.0:4200/api"
